/**
 * Created by dwight on 17/08/15.
 */
package object champs {


  val SCHOOLS: Map[String, List[String]] =
    Map(
      "Aabuthnott Gallimore High" -> List("Aabuthnott Galli", "Aabuthnott G"),
      "Aberdeen High School" -> List("Aberdeen High"),
      "Albert Town High" -> List("Albert Town"),
      "Alpha Academy" -> List("Alpha", "Convent of M", "Convent OF Mercy", "Convent of Mercy", "Convent OF", "Convent of Mercy Alpha Academy", "Convent of Mercy Academy", "Convent of Mercy Alpha", "Convent OF Mercy Academy Alpha"),
      "Alston High" -> List(),
      "America International School" -> List("America Int. Sch", "American Int"),
      "Anchovy High" -> List("Anchovy", "Anchovy High"),
      "Annotto Bay High" -> List("Annotto Bay High", "Annotto Bay", "Annotto Bay High School"),
      "Ardenne High" -> List("Ardenne High School"),
      "Ascot High" -> List("Ascot High School"),
      "B. B. Coke High" -> List("B.B. Coke High School", "B.B. Coke High", "B.B. Coke", "BB Coke", "B B Coke High"),
      "Balaclava High" -> List("Balaclava", "Balaclava High S"),
      "Belair High" -> List("Belair High School"),
      "Bellefield High" -> List("Bellefield", "Bellefield High School"),
      "Belmont Academy" -> List(),
      "Black River High" -> List(),
      "Bog Walk High" -> List("Bogwalk High Sch", "Bogwalk High Sc", "Bogwalk High School"),
      "Bridgeport High" -> List("Bridgeport High School"),
      "Brimmer Vale High" -> List(),
      "Brown's Town High" -> List("Browns Town High"),
      "Buff Bay High" -> List("Buff Bay High School"),
      "Bustamante High" -> List(),
      "Calabar High School" -> List("Calabar", "Calabar High", "cbar"),
      "Cambridge High" -> List(),
      "Camperdown High" -> List("Camperdown High", "Camperdown", "Camperdown High School"),
      "Campion College" -> List("Campion"),
      "Carron Hall High" -> List(),
      "Cedric Titus" -> List("Cedric Titus High"),
      "Central High" -> List("Central High School"),
      "Charlemont High" -> List("Charlemont High School"),
      "Charlie Smith High" -> List("charlie smith high", "Charlie Smith"),
      "City College" -> List(),
      "Clan Carthy High" -> List("Clan Carthy", "Clan Carthy High School"),
      "Clarendon College" -> List(),
      "Claude McKay High" -> List("Claude McKay", "Claude McKay High School"),
      "Cornwall College" -> List("Cornwall"),
      "Cross Keys High" -> List("Cross Keys High School"),
      "Cumberland High School" -> List("Cumberland", "Cumberland High"),
      "Decarteret College" -> List("DeCarteret College"),
      "Denham Town High" -> List(),
      "Denbigh High" -> List("Denbigh High", "Denbigh High Sch", "Denbigh High School"),
      "Dinthill Technical High" -> List("Dinthill Tech", "Dinthill Tech High", "Dinthill Techn", "Dinthill Tec", "Dinthill High", "Dinthill High School", "Dinthill Technical", "Dinthill Technical High School"),
      "Donald Quarrie High" -> List("Donald Quarrie H", "Donald Quarrie", "Donald Quarrie High School", "donald quarrie high"),
      "Dunoon Technical High" -> List("Dunoon Technical", "Dunoon Park", "Dunoon Tech", "Dunoon Tech High", "Dunoon Park Tech"),
      "Edith Dalton James" -> List("Edith Dalton", "Edith Darlton James", "Edith Dalton James Blazers", "Edith Dalton James High", "Edith Dalton High"),
      "Edwin Allen High" -> List("Edwin Allen High School", "Edwin Allen"),
      "Eltham High" -> List("Eltham", "Eltham High School"),
      "Excelsior High" -> List("XLCR", "Excelsior High S", "Excelsior High School", "Excelsior", "Xlcr-G"),
      "Ewarton High" -> List(),
      "Fair Prospect" -> List("fair prospec", "Fair Prospect High"),
      "Ferncourt High" -> List("Ferncourt High School"),
      "Foga Road High" -> List("Foga Road"),
      "Frome Technical High" -> List("Frome Tech", "Frome Techni", "Frome Technical", "Frome"),
      "Gaynstead High School" -> List("Gaynstead High"),
      "Garvey Maceo High" -> List("Garvey Maceo", "Garvey MACEO High", "Garvey Maceo High School"),
      "Glengoffe High" -> List("Glengoffe High S", "Glengoffe High School", "Glengoffe"),
      "Glenmuir High" -> List("Glenmuir High School"),
      "Godfrey Stewart High" -> List("Godfrey Stew", "Godfrey Stewart"),
      "Grange Hill High" -> List("Grange Hill"),
      "Greater Portmore" -> List("Greater Port", "Greater Portmore High", "Greater Portmore High School"),
      "Green Island High" -> List("Green Island", "Green Island High School"),
      "Green Pond High" -> List("Green Pond"),
      "Guys Hill High" -> List("Guys Hill"),
      "Haile Selassie High" -> List(),
      "Hampton School" -> List("Hampton High", "Hampton", "Hampton School for Girls"),
      "Happy Grove High" -> List("Happy Grove", "Happy Grove High School"),
      "Herbert Morrison" -> List("Herbert Morrison High", "Herbert Morr", "Herbert Morrison Technical Hi", "Herbert Morrison Technical Hig", "Herbert Morrison Technical"),
      "Holmwood Technical High" -> List("Holmwood Techn", "Holmwood", "Holmwood Tech", "Holmwood Tec", "Holmwood Technical", "Holmwood Technic", "Holmwood Technical High School"),
      "Holland High" -> List("Holland High School", "Holland"),
      "Holy Trinity High" -> List("Holy Trinity"),
      "Hopewell High" -> List("Hopewell"),
      "Holy Childhood High" -> List("Holy Childhood High School", "Holy Childhood"),
      "Hydel Group of Schools" -> List("Hydel Group", "Hydel High", "Hydel High School"),
      "Innswood High School" -> List("Innswood High"),
      "Iona High School" -> List("Iona High"),
      "Immaculate Conception High" -> List("Immaculate", "Immaculate C", "Immaculate Conce", "Immaculate High"),
      "Innswood High School" -> List("Innswood", "Innswood High"),
      "Irwin High" -> List("Irwin", "Irwin High School"),
      "Jamaica College" -> List("jc", "JC"),
      "Jose Marti Technical High" -> List("Jose Marti Technical Hig", "Jose Marti T", "Jose Marti Technical", "Jose Marti", "Jose Marti Tech"),
      "Jonathan Grant High" -> List("Jonathan Grant", "Jonathan Grant High School"),
      "Kellits High" -> List("Kellits High Sch", "Kellits High School"),
      "Kemps Hill High" -> List("Kemps Hill High School", "Kemps Hill"),
      "Kingston College" -> List("KC", "kc", "Kc"),
      "Kingston High School" -> List("Kingston High"),
      "Kingston Technical High" -> List("Kingston Technical", "Kingston Tech"),
      "Knox College" -> List(),
      "Lacovia High" -> List("Lacovia", "Lacovia High School"),
      "Lennon High" -> List("Lennon High School"),
      "Lewisville High" -> List("Lewisville"),
      "Little London High" -> List("Little London"),
      "Louise Bennet-Coverly High" -> List("Louise Bennet-Co", "Louise Bennett C", "Louise Bennett-Co", "Louise Bennett"),
      "Maggotty High School" -> List("Maggotty High", "Maggotty"),
      "Maldon High" -> List(),
      "Manchester High" -> List("Manchester High School"),
      "Manning's High" -> List("Mannings", "Mannings High SC", "Mannings High"),
      "Marcus Garvey Technical High" -> List("Marcus Garvey TE", "Marcus Garvey Te", "Marcus Garve"),
      "Marymount High" -> List("Marymount High School"),
      "Maud McLeod High" -> List("Maud McLeod"),
      "Mavis Bank High" -> List("Mavis Bank High School", "Mavis Bank"),
      "May Day High" -> List(),
      "McGrath High" -> List("McGrath High School", "Mcgrath High School"),
      "Merlene Ottey High" -> List("Merlene Ottey"),
      "Merl Grove High" -> List("Merl Grove", "Merl Grove High School"),
      "Mile Gully High" -> List("Mile Gully"),
      "Mineral Heights High" -> List("Mineral Heights"),
      "Montego Bay High" -> List("Mobay High"),
      "Mona High" -> List("Mona High School"),
      "Meadowbrook High" -> List("Meadowbrook Hig", "Meadowbrook High School", "Meadowbrook"),
      "Morant Bay High" -> List("Morant Bay High School"),
      "Mt. Alvernia High" -> List("Mount Alvernia High", "MT Alvernia High", "Mt. Alvernia", "Mt Alvernia High"),
      "Munro College" -> List("Munro"),
      "Muschett High" -> List("Muschette", "Muschett"),
      "Newell High" -> List("Newell"),
      "Norman Manley High School" -> List("Norman Manley High"),
      "Oberlin High" -> List("Oberlin High S", "Oberlin High SC", "Oberlin High School"),
      "Ocho Rios High" -> List("Ocho Rios Hig"),
      "Old Harbour High" -> List("Old Harbour", "Old Harbour High School"),
      "Oracabessa High" -> List(),
      "Paul Bogle High School" -> List("Paul Bogle", "Paul Bogle High"),
      "Papine High" -> List("Papine High School", "Papine"),
      "Pembrook Hall High" -> List("Pembrooke Hall High", "Pembrooke Hall H", "Pembrooke Hall", "Pembroke Hall High", "Pembroke Hall High School", "Pembroke Hall"),
      "Penwood High School" -> List("Penwood High"),
      "Petersfield High" -> List("Petersfield", "Petersfield High School"),
      "Port Antonio High" -> List("Port Antonio Hig"),
      "Port Morant High School" -> List("Port Morant"),
      "Porus High School" -> List("High School"),
      "Robert Lightbourne" -> List("Robert Lightbourne High", "Robert Light"),
      "Rhodes Hall High" -> List("Rhodes Hall"),
      "Rusea's High" -> List("Rusea's High School", "Ruseas High School", "Ruseas High", "Ruseas"),
      "Seaforth High" -> List("Seaforth High School", "Seaforth"),
      "Spaldings High" -> List("Spalding High", "Spalding", "Spaulding High", "Spaulding High School", "Spalding High School"),
      "Spanish Town High" -> List("Spanish Town HI"),
      "Spot Valley High" -> List("Spot Valley"),
      "Steer Town Academy" -> List(),
      "St. Andrew College" -> List("ST Andrew Colleg"),
      "St. Andrew High for Girls" -> List("St.Andrews", "St Andrew High", "St. Andrew High", "St. Andrew H", "St. Andrew High School", "St Andrew High School", "ST Andrew High For Girls"),
      "St. Andrew Technical High" -> List("St. Andrew Tech", "St Andrew Technical High", "St. Andrew T", "St. Andrew Techn", "Staths", "St. Andrew Technical", "St. Andrew Technical High School"),
      "St. Catherine High" -> List("St. Catherine High School", "St Catherine High", "St.Catherine High", "ST Catherine Hig", "St Catherine Hig", "ST Catherine High", "St. Catherine"),
      "St. Elizabeth Technical High" -> List("St. Elizabeth", "St. Elizabet", "Steths", "STETHS", "St. Elizabeth Technical", "ST Elizabeth Technical High"),
      "St. George's College" -> List("St. Georges", "St Georges College", "St. George's Col", "St George's College", "Saint Georges CO", "St. George's", "ST Georges College", "St. Georges College", "St. Georges Colle"),
      "St. Hugh's High" -> List("ST Hugh's High", "St. Hughs High", "St. Hugh", "St. Hughs High School", "St Hughs High School"),
      "St. Jago High" -> List("St. Jago", "St Jago High", "St. Jago High SC", "Jago", "jago", "St. Jago High Girls", "St. Jago High Boys", "St. Jago Boys", "St. Jago Girls", "ST Jago High School", "St. Jago High School", "St Jago High School", "St.Jago"),
      "St. James High" -> List("ST James High"),
      "St. Joseph High School" -> List("St Josephs High"),
      "St. Mary High" -> List("St. Mary High", "St Mary High School"),
      "St. Mary's College" -> List("St. Mary's Colle", "St. Marys College", "St Mary's College"),
      "St. Mary Technical" -> List("St. Mary Technic", "St. Mary Technical High", "St. Mary Tech", "St Mary Tech"),
      "St. Thomas Technical" -> List("St. Thomas T", "St. Thomas Techn", "St. Thomas Technical High", "St. Thomas Tec", "St. Thomas Tech"),
      "Tacius Golding High" -> List("Tacius Golding", "Tacius Golding High School"),
      "Tacky High" -> List("Tacky High School"),
      "Tarrant High School" -> List("Tarrant High"),
      "Titchfield High School" -> List("Titchfield High", "Titchfield"),
      "Tivoli Gardens High" -> List("Tivoli Gardens H", "Tivoli Gardens", "Tivoli Gardens High School", "Tivoli"),
      "The Queens School" -> List("The Queen's School", "Queens"),
      "Thompson Town High" -> List("Thompson Town", "Thompson Town High School"),
      "Troy High" -> List(),
      "Vauxhall High" -> List("Vauxhall High School", "Vauxhall"),
      "Vere Technical High" -> List("Vere Technical H", "Vere Technical", "Vere Technical High School", "Vere Technic", "Vere Tech"),
      "Waterford High School" -> List("Waterford High"),
      "Westwood High School" -> List("Westwood High", "Westwood"),
      "William Knibb Memorial High" -> List("William Knib", "William Knibb High", "William Knibb"),
      "Winston Jones High" -> List(),
      "Wolmer's High" -> List("Wolmer's Boys", "Wolmer's High School for Girls", "Wolmer's Girls", "Wolmer's High School for Boys", "Wolmer's Hig"),
      "Yallahs High" -> List("Yallahs High School", "Yallahs"),
      "York Castle High" -> List("YorkCastle High", "York Castle", "York Castle High School")
    )

}
